# Generated by Django 5.0.2 on 2024-04-23 07:26

import django.db.models.deletion
import embed_video.fields
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='yid', unique=True)),
                ('title', models.CharField(max_length=180)),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=280, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.author')),
            ],
        ),
    ]
