# Generated by Django 5.0.6 on 2024-06-26 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
